### ISSUE TITLE
"I am a web, … develop."

### ISSUE THREAD

**Issue by martinjdavidson** [ecnepsnai/Blog#1]
On your 'Contact Me'<https://ianspence.com/>,  please consider appending an "er" onto the word "develop" so your statement ("I am a web, … develop.") makes sense. Had to mention it — just a little bit of OCD [obsessive compulsive disorder]. 

  Good day!

**Comment by martinjdavidson** [comment]
Thanks.

**Comment by ecnepsnai** [comment]
Ah, I missed that.  Thank you.
